import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join, relative, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkRehype from 'remark-rehype';
import rehypeRaw from 'rehype-raw';
import { D2 } from '@terrastruct/d2';
import rehypeHighlight from 'rehype-highlight';
import rehypeSanitize, { defaultSchema } from 'rehype-sanitize';
import rehypeStringify from 'rehype-stringify';
import { resolvePackInputs } from './pack-resolver.mjs';
import { createSourceVersion, sourcePathForWriteback, WRITEBACK_CONTRACT_VERSION } from './writeback.mjs';

const require = createRequire(import.meta.url);
const moduleDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(moduleDir, '..');
const themePath = join(projectRoot, 'src', 'theme', 'agent-theme.css');
const componentBundlePath = join(projectRoot, 'dist', 'agent-components.js');
const componentScriptName = 'agent-components.js';
const mermaidRuntimePath = require.resolve('mermaid/dist/mermaid.min.js');
const mermaidRuntimeName = 'mermaid.min.js';
const mermaidCdnUrl = 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js';
const markdownExtensions = new Set(['.md', '.markdown']);
const localAssetDirName = 'assets';
const packAssetRootPath = `${localAssetDirName}/agent-isles/packs`;
const packMetadataPath = `${localAssetDirName}/agent-isles/packs.json`;
const localAssets = [
  {
    source: require.resolve('bootstrap/dist/css/bootstrap.min.css'),
    fileName: 'bootstrap.min.css',
  },
  {
    source: require.resolve('bootstrap/dist/css/bootstrap.min.css.map'),
    fileName: 'bootstrap.min.css.map',
  },
  {
    source: require.resolve('highlight.js/styles/github-dark.min.css'),
    fileName: 'github-dark.min.css',
  },
  {
    source: require.resolve('bootstrap/dist/js/bootstrap.bundle.min.js'),
    fileName: 'bootstrap.bundle.min.js',
  },
  {
    source: require.resolve('bootstrap/dist/js/bootstrap.bundle.min.js.map'),
    fileName: 'bootstrap.bundle.min.js.map',
  },
];

export class AgentIslesInputError extends Error {
  constructor(message, code) {
    super(message);
    this.name = 'AgentIslesInputError';
    this.code = code;
  }
}

export function validateMarkdownInput(inputPath) {
  const filePath = resolve(inputPath);

  if (!existsSync(filePath)) {
    throw new AgentIslesInputError(
      `Input file not found: ${filePath}`,
      'ERR_AGENT_ISLES_INPUT_NOT_FOUND',
    );
  }

  const extension = extname(filePath).toLowerCase();
  if (!markdownExtensions.has(extension)) {
    throw new AgentIslesInputError(
      `Unsupported input file extension: ${filePath}\nExpected a Markdown file ending in .md or .markdown.`,
      'ERR_AGENT_ISLES_UNSUPPORTED_INPUT_EXTENSION',
    );
  }

  return filePath;
}

export const RENDER_MODES = Object.freeze({
  TRUSTED: 'trusted',
  SANITIZED: 'sanitized',
});

const coreSanitizedSchema = {
  ...defaultSchema,
  tagNames: [
    ...new Set([
      ...(defaultSchema.tagNames || []),
      'agent-decision',
      'agent-risk',
      'agent-metric',
      'agent-delta',
      'agent-copy-block',
      'agent-tabs',
      'agent-tab',
      'agent-timeline',
      'agent-step',
      'agent-gantt',
      'agent-gantt-phase',
      'agent-gantt-task',
      'agent-kpi',
      'agent-status-board',
      'agent-status-item',
      'agent-dependency-map',
      'agent-dependency',
      'agent-action-list',
      'agent-action',
      'agent-kanban',
      'agent-kanban-lane',
      'agent-kanban-card',
      // D2 diagram support (generated by rehype-d2)
      'figure',
      'svg',
      'g',
      'rect',
      'path',
      'text',
      'tspan',
      'defs',
      'marker',
      'line',
      'polygon',
      'polyline',
      'circle',
      'ellipse',
      'clipPath',
      'mask',
      'use',
      'style',
      'title',
      'desc',
    ]),
  ],
  attributes: {
    ...defaultSchema.attributes,
    '*': [
      'className',
      'data*',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.['*'] || []),
    ],
    a: [
      'className',
      'target',
      'rel',
      'role',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.a || []),
    ],
    div: [
      'className',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.div || []),
    ],
    span: [
      'className',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.span || []),
    ],
    img: [
      'className',
      'alt',
      'src',
      'title',
      'role',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.img || []),
    ],
    code: ['className', ...(defaultSchema.attributes?.code || [])],
    pre: ['className', 'data*', ...(defaultSchema.attributes?.pre || [])],
    'agent-decision': ['className', 'title', 'verdict'],
    'agent-risk': ['className', 'title', 'level'],
    'agent-metric': ['className', 'label', 'value', 'unit', 'trend', 'tone'],
    'agent-delta': ['className', 'label', 'value', 'unit', 'percent', 'direction', 'tone'],
    'agent-copy-block': ['className', 'label', 'lang'],
    'agent-tabs': ['className', 'label'],
    'agent-tab': ['className', 'title', 'active'],
    'agent-timeline': ['className', 'label'],
    'agent-step': ['className', 'status', 'label'],
    'agent-gantt': ['className', 'weeks', 'milestones', 'label'],
    'agent-gantt-phase': ['className', 'label'],
    'agent-gantt-task': ['className', 'label', 'start', 'end', 'tone', 'detail', 'parallel'],
    'agent-kpi': ['className', 'label', 'value', 'unit', 'delta', 'tone'],
    'agent-status-board': ['className', 'label', 'meta', 'summary', 'group-by', 'hide-empty-groups'],
    'agent-status-item': ['className', 'label', 'status', 'status-color', 'status-label', 'owner', 'updated', 'history'],
    'agent-dependency-map': ['className', 'label', 'direction', 'legend'],
    'agent-dependency': [
      'className',
      'id',
      'label',
      'status',
      'blockedBy',
      'blocked-by',
      'owner',
      'priority',
      'href',
    ],
    'agent-action-list': [
      'className',
      'label',
      'layout',
      'group-by',
      'filter-status',
      'filter-priority',
      'show-done',
    ],
    'agent-action': ['className', 'owner', 'due', 'priority', 'status'],
    'agent-kanban': ['className', 'label', 'lanes', 'density'],
    'agent-kanban-lane': ['className', 'key', 'label', 'empty'],
    'agent-kanban-card': ['className', 'title', 'owner', 'meta', 'priority', 'status', 'tone'],
    // D2 diagram SVG attributes
    figure: ['className', 'data*'],
    svg: [
      'className',
      'xmlns',
      'xmlnsXlink',
      'xmlns:xlink',
      'viewBox',
      'width',
      'height',
      'preserveAspectRatio',
    ],
    g: ['className', 'id', 'transform', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    rect: [
      'className',
      'x',
      'y',
      'width',
      'height',
      'rx',
      'ry',
      'fill',
      'stroke',
      'strokeWidth',
      'stroke-width',
    ],
    path: ['className', 'd', 'fill', 'stroke', 'strokeWidth', 'stroke-width', 'transform'],
    text: [
      'className',
      'x',
      'y',
      'dx',
      'dy',
      'fill',
      'fontSize',
      'font-size',
      'fontFamily',
      'font-family',
      'fontWeight',
      'font-weight',
      'textAnchor',
      'text-anchor',
      'dominantBaseline',
      'dominant-baseline',
      'transform',
    ],
    tspan: [
      'className',
      'x',
      'y',
      'dx',
      'dy',
      'fill',
      'fontSize',
      'font-size',
      'fontWeight',
      'font-weight',
    ],
    line: [
      'className',
      'x1',
      'y1',
      'x2',
      'y2',
      'stroke',
      'strokeWidth',
      'stroke-width',
      'markerStart',
      'marker-start',
      'markerEnd',
      'marker-end',
    ],
    polygon: ['className', 'points', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    polyline: ['className', 'points', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    circle: ['className', 'cx', 'cy', 'r', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    ellipse: [
      'className',
      'cx',
      'cy',
      'rx',
      'ry',
      'fill',
      'stroke',
      'strokeWidth',
      'stroke-width',
    ],
    marker: [
      'className',
      'id',
      'markerWidth',
      'markerHeight',
      'refX',
      'refY',
      'orient',
      'markerUnits',
    ],
    defs: ['className'],
    clipPath: ['className', 'id'],
    mask: ['className', 'id'],
    use: ['className', 'href', 'xlinkHref', 'xlink:href', 'x', 'y'],
  },
};

function buildSanitizedSchema(resolvedPacks) {
  const tagNames = new Set(coreSanitizedSchema.tagNames || []);
  const attributes = copySchemaAttributes(coreSanitizedSchema.attributes);

  for (const pack of resolvedPacks?.packs || []) {
    for (const tag of pack.tags || []) {
      if (!tag?.name) {
        continue;
      }

      tagNames.add(tag.name);
      const declaredAttributes = (tag.attributes || []).filter(isSafePackDeclaredAttribute);
      if (declaredAttributes.length === 0) {
        continue;
      }

      attributes[tag.name] = [
        ...new Set([
          ...(attributes[tag.name] || []),
          ...declaredAttributes,
        ]),
      ];
    }
  }

  return {
    ...coreSanitizedSchema,
    tagNames: [...tagNames],
    attributes,
  };
}

function copySchemaAttributes(attributes = {}) {
  return Object.fromEntries(
    Object.entries(attributes).map(([tagName, allowedAttributes]) => [
      tagName,
      [...allowedAttributes],
    ]),
  );
}

function isSafePackDeclaredAttribute(attributeName) {
  const normalizedName = String(attributeName).toLowerCase();

  return !normalizedName.startsWith('on') && normalizedName !== 'style' && normalizedName !== 'srcdoc';
}

export async function renderMarkdown(markdown, options = {}) {
  const renderMode = normalizeRenderMode(options.renderMode);
  const assetMode = normalizeAssetMode(options.assetMode);
  const sourceMarkdown = typeof options.sourceMarkdown === 'string' ? options.sourceMarkdown : markdown;
  const markdownTaskMarkers = buildMarkdownTaskMarkerRecords(sourceMarkdown);
  const toc = [];
  const processor = unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype, { allowDangerousHtml: true })
    .use(rehypeAgentMermaid)
    .use(rehypeAgentD2)
    .use(rehypeRaw)
    .use(rehypeAgentWritebackMetadata, {
      ...options,
      sourceMarkdown,
      markdownTaskMarkers,
    });

  if (renderMode === RENDER_MODES.SANITIZED) {
    processor
      .use(dropUnsafeRawHtmlElements)
      .use(rehypeSanitize, buildSanitizedSchema(options.resolvedPacks));
  }

  processor.use(rehypeAgentHeadingAnchors, { toc });

  const body = await processor
    .use(rehypeHighlight)
    .use(rehypeStringify, { allowDangerousHtml: renderMode === RENDER_MODES.TRUSTED })
    .process(markdown);

  return buildHtmlPage(String(body), { ...options, renderMode, assetMode, sourceMarkdown, toc });
}

export async function renderMarkdownString(markdown, options = {}) {
  const assetMode = normalizeAssetMode(options.assetMode);
  const resolvedPacks = await resolvePackInputs({
    explicitPacks: options.explicitPacks || [],
    projectDir: options.projectDir ?? process.cwd(),
    includeUserPacks: options.includeUserPacks === true,
    userConfigDir: options.userConfigDir || null,
  });
  const packAssetRecords = buildPackAssetRecords(resolvedPacks.packs);
  const html = await renderMarkdown(markdown, {
    ...options,
    assetMode,
    resolvedPacks,
    packAssetRecords,
  });

  return { html, resolvedPacks, packAssetRecords, assetMode };
}

export async function renderMarkdownFile(inputPath, options = {}) {
  const filePath = validateMarkdownInput(inputPath);
  const markdown = readFileSync(filePath, 'utf8');
  const outFile = options.outFile ? resolve(options.outFile) : undefined;
  const { html, resolvedPacks, packAssetRecords, assetMode } = await renderMarkdownString(markdown, {
    ...options,
    sourcePath: filePath,
    projectDir: options.projectDir ?? dirname(filePath),
  });

  if (outFile) {
    mkdirSync(dirname(outFile), { recursive: true });
    writeFileSync(outFile, html);
    if (assetMode !== 'inline') {
      copyComponentBundle(dirname(outFile));
      if (assetMode === 'local') {
        copyLocalAssets(dirname(outFile));
        if (hasMermaidDiagrams(html)) {
          copyMermaidRuntime(dirname(outFile));
        }
      }
      copyPackAssets(dirname(outFile), packAssetRecords);
      writePackMetadata(dirname(outFile), packAssetRecords);
    }
  }

  return { html, outFile, resolvedPacks };
}

function rehypeAgentMermaid() {
  return (tree) => {
    transformMermaidCodeBlocks(tree);
  };
}

function transformMermaidCodeBlocks(node) {
  if (!Array.isArray(node.children)) {
    return;
  }

  for (let index = 0; index < node.children.length; index += 1) {
    const child = node.children[index];
    const mermaidCode = extractLanguageCodeBlock(child, 'mermaid');

    if (mermaidCode) {
      node.children[index] = {
        type: 'element',
        tagName: 'figure',
        properties: { className: ['agent-mermaid'], dataAgentMermaid: true },
        children: [
          {
            type: 'element',
            tagName: 'pre',
            properties: { className: ['mermaid'], dataAgentMermaidSource: true },
            children: [{ type: 'text', value: mermaidCode.value }],
          },
        ],
      };
      continue;
    }

    transformMermaidCodeBlocks(child);
  }
}

function rehypeAgentD2() {
  return async (tree) => {
    await transformD2CodeBlocks(tree);
  };
}

async function transformD2CodeBlocks(node) {
  if (!Array.isArray(node.children)) {
    return;
  }

  for (let index = 0; index < node.children.length; index += 1) {
    const child = node.children[index];
    const d2Code = extractLanguageCodeBlock(child, 'd2');

    if (d2Code) {
      const svg = await renderD2Svg(d2Code.value, child.position);
      node.children[index] = {
        type: 'element',
        tagName: 'figure',
        properties: { className: ['beoe', 'd2'] },
        children: [{ type: 'raw', value: svg }],
      };
      continue;
    }

    await transformD2CodeBlocks(child);
  }
}

function extractLanguageCodeBlock(node, language) {
  if (node?.type !== 'element' || node.tagName !== 'pre') {
    return null;
  }

  const codeNode = node.children?.find((child) => child.type === 'element' && child.tagName === 'code');
  const classNames = codeNode?.properties?.className || [];
  const languageClassName = `language-${language}`;
  const hasLanguage = Array.isArray(classNames)
    ? classNames.includes(languageClassName)
    : String(classNames).split(/\s+/).includes(languageClassName);

  if (!hasLanguage) {
    return null;
  }

  return {
    value: codeNode.children?.map((child) => child.value || '').join('') || '',
  };
}

async function renderD2Svg(source, position) {
  const d2 = new D2();

  try {
    const result = await d2.compile(source, { noXMLTag: true });
    return await d2.render(result.diagram, { ...result.renderOptions, noXMLTag: true });
  } catch (error) {
    const location = formatPosition(position);
    const message = error?.message || String(error);
    throw new Error(`D2 diagram render failed${location}: ${message}`);
  } finally {
    await d2.worker?.terminate?.();
  }
}

function formatPosition(position) {
  const start = position?.start;
  if (!start?.line) {
    return '';
  }

  return ` at line ${start.line}${start.column ? `, column ${start.column}` : ''}`;
}

export function defaultOutFile(inputPath) {
  const filePath = resolve(inputPath);
  const ext = extname(filePath);
  const baseName = basename(ext ? filePath.slice(0, -ext.length) : filePath);
  return resolve('dist', `${baseName || 'output'}.html`);
}

export function normalizeRenderMode(renderMode = RENDER_MODES.TRUSTED) {
  if (renderMode === RENDER_MODES.TRUSTED || renderMode === RENDER_MODES.SANITIZED) {
    return renderMode;
  }

  throw new Error(
    `Unknown render mode: ${renderMode}. Use "${RENDER_MODES.TRUSTED}" or "${RENDER_MODES.SANITIZED}".`,
  );
}

function dropUnsafeRawHtmlElements() {
  const blockedTagNames = new Set(['script', 'style', 'iframe', 'object', 'embed']);

  return (tree) => {
    visitChildren(tree, (children, index, node) => {
      if (node.type === 'element' && blockedTagNames.has(node.tagName)) {
        children.splice(index, 1);
        return index;
      }

      return undefined;
    });
  };
}

function rehypeAgentHeadingAnchors(options = {}) {
  return (tree) => {
    const toc = options.toc || [];
    const seenIds = new Map();

    visitChildren(tree, (children, index, node) => {
      if (node?.type !== 'element' || !/^h[1-6]$/.test(node.tagName)) {
        return undefined;
      }

      const text = plainText(node).replace(/\s+/g, ' ').trim();
      if (!text) {
        return undefined;
      }

      node.properties ||= {};
      const level = Number(node.tagName.slice(1));
      const existingId = readStringProperty(node.properties, 'id');
      const id = existingId || uniqueHeadingId(slugifyHeading(text), seenIds);

      if (level <= 3) {
        toc.push({ id, text, level });
      }

      if (!existingId) {
        children.splice(index, 0, {
          type: 'element',
          tagName: 'span',
          properties: { id, className: ['agent-isles-heading-anchor'], ariaHidden: 'true' },
          children: [],
        });
        return index + 2;
      }

      return undefined;
    });
  };
}

function plainText(node) {
  if (!node) {
    return '';
  }
  if (node.type === 'text') {
    return node.value || '';
  }
  if (!Array.isArray(node.children)) {
    return '';
  }
  return node.children.map(plainText).join('');
}

function slugifyHeading(text) {
  const slug = String(text)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');

  return slug || 'section';
}

function uniqueHeadingId(baseId, seenIds) {
  const count = seenIds.get(baseId) || 0;
  seenIds.set(baseId, count + 1);
  return count === 0 ? baseId : `${baseId}-${count + 1}`;
}

function visitChildren(node, visitor) {
  if (!Array.isArray(node.children)) {
    return;
  }

  for (let index = 0; index < node.children.length; index += 1) {
    const child = node.children[index];
    const nextIndex = visitor(node.children, index, child, node);

    if (typeof nextIndex === 'number') {
      index = nextIndex - 1;
      continue;
    }

    visitChildren(child, visitor);
  }
}

function rehypeAgentWritebackMetadata(options = {}) {
  return (tree) => {
    const writebackOptions = options.writeback || {};
    const enabled = writebackOptions.enabled === true;
    const markdownTaskMarkers = options.markdownTaskMarkers || [];
    let generatedId = 0;
    let markdownTaskIndex = 0;

    visitChildren(tree, (_children, _index, node, parent) => {
      if (node?.type !== 'element') {
        return undefined;
      }

      const operationType = readWritebackOperationType(node.properties);
      stripWritebackProperties(node.properties);

      if (isMarkdownTaskCheckboxInput(node, parent, _index)) {
        const marker = markdownTaskMarkers[markdownTaskIndex];
        markdownTaskIndex += 1;

        if (!enabled || !marker) {
          return undefined;
        }

        const sourcePath = sourcePathForWriteback(options.sourcePath, writebackOptions.rootPath);
        if (!sourcePath) {
          return undefined;
        }

        delete node.properties.disabled;
        node.properties['aria-label'] = marker.checked ? 'Mark task incomplete' : 'Mark task complete';
        node.properties['data-agent-isles-writeback'] = JSON.stringify({
          contractVersion: WRITEBACK_CONTRACT_VERSION,
          sourcePath,
          sourceVersion: createSourceVersion(options.sourceMarkdown || ''),
          target: {
            kind: 'markdown-task-checkbox',
            tagName: 'input',
            range: marker.range,
            anchor: { text: marker.marker },
          },
          operation: { type: 'markdown:set-task-checkbox' },
        });
        return undefined;
      }

      if (!enabled || !operationType) {
        return undefined;
      }

      if (!isAgentComponentTag(node.tagName) || !node.position?.start || !node.position?.end) {
        return undefined;
      }

      generatedId += 1;
      const componentId = readStringProperty(node.properties, 'id') || `${node.tagName}-${generatedId}`;
      const sourcePath = sourcePathForWriteback(options.sourcePath, writebackOptions.rootPath);
      if (!sourcePath) {
        return undefined;
      }

      const metadata = {
        contractVersion: WRITEBACK_CONTRACT_VERSION,
        sourcePath,
        sourceVersion: createSourceVersion(options.sourceMarkdown || ''),
        target: {
          componentId,
          tagName: node.tagName,
          range: {
            start: copyPositionPoint(node.position.start),
            end: copyPositionPoint(node.position.end),
          },
        },
        operation: { type: operationType },
      };

      node.properties['data-agent-isles-writeback'] = JSON.stringify(metadata);
      return undefined;
    });
  };
}

function isMarkdownTaskCheckboxInput(node, parent, index) {
  if (node?.tagName !== 'input') {
    return false;
  }

  const properties = node.properties || {};
  const isCheckbox = readStringProperty(properties, 'type') === 'checkbox' || properties.type === 'checkbox';
  if (!isCheckbox || !Object.hasOwn(properties, 'disabled')) {
    return false;
  }

  return index === 0 && parent?.tagName === 'li' && hasClassName(parent.properties, 'task-list-item');
}

function hasClassName(properties = {}, className) {
  const value = properties.className;
  if (Array.isArray(value)) {
    return value.includes(className);
  }
  if (typeof value === 'string') {
    return value.split(/\s+/).includes(className);
  }
  return false;
}

function buildMarkdownTaskMarkerRecords(markdown) {
  const records = [];
  const source = String(markdown || '');
  const linePattern = /.*(?:\r\n|\n|\r|$)/g;
  let match;

  while ((match = linePattern.exec(source)) !== null) {
    const lineWithEnding = match[0];
    if (lineWithEnding === '') {
      break;
    }

    const lineOffset = match.index;
    const lineNumber = recordsLineNumber(source, lineOffset);
    const lineWithoutEnding = lineWithEnding.replace(/\r\n|\n|\r$/, '');
    const taskMatch = lineWithoutEnding.match(/^([ \t]*(?:[-+*]|\d+[.)])[ \t]+)(\[[ xX]\])(?=\s|$)/);
    if (taskMatch) {
      const markerOffset = lineOffset + taskMatch[1].length;
      const markerColumn = taskMatch[1].length + 1;
      const marker = taskMatch[2];
      records.push({
        marker,
        checked: marker === '[x]' || marker === '[X]',
        range: {
          start: { line: lineNumber, column: markerColumn, offset: markerOffset },
          end: { line: lineNumber, column: markerColumn + marker.length, offset: markerOffset + marker.length },
        },
      });
    }

    if (linePattern.lastIndex >= source.length) {
      break;
    }
  }

  return records;
}

function recordsLineNumber(source, offset) {
  let line = 1;
  for (let index = 0; index < offset; index += 1) {
    if (source[index] === '\n') {
      line += 1;
    }
  }
  return line;
}

function readWritebackOperationType(properties = {}) {
  return readStringProperty(properties, 'data-agent-isles-writeback-op')
    || readStringProperty(properties, 'dataAgentIslesWritebackOp');
}

function stripWritebackProperties(properties = {}) {
  delete properties['data-agent-isles-writeback-op'];
  delete properties.dataAgentIslesWritebackOp;
  delete properties['data-agent-isles-writeback'];
  delete properties.dataAgentIslesWriteback;
}

function readStringProperty(properties = {}, propertyName) {
  const value = properties[propertyName];
  if (typeof value === 'string') {
    return value;
  }
  if (typeof value === 'number') {
    return String(value);
  }
  return null;
}

function isAgentComponentTag(tagName) {
  return typeof tagName === 'string' && tagName.startsWith('agent-');
}

function copyPositionPoint(point) {
  const copy = {
    line: point.line,
    column: point.column,
  };

  if (Number.isInteger(point.offset)) {
    copy.offset = point.offset;
  }

  return copy;
}

function buildHtmlPage(body, options = {}) {
  const title = options.title || 'Agent Isles Output';
  const assetMode = normalizeAssetMode(options.assetMode);
  const theme = readTheme();
  const packAssetRecords = options.packAssetRecords || buildPackAssetRecords(options.resolvedPacks?.packs || []);
  const mainClass = options.showSource
    ? 'agent-isles-page agent-isles-page--source-view container-fluid py-4'
    : 'agent-isles-page container py-4';
  const pageBody = options.showSource ? buildSourceComparison(body, options.sourceMarkdown || '') : body;
  const missingBundleComment = existsSync(componentBundlePath)
    ? ''
    : '\n  <!-- Agent Isles warning: dist/agent-components.js is missing. Run `npm run build`. -->';
  const styles = buildStyles(assetMode);
  const scripts = buildScripts(assetMode, missingBundleComment);
  const writebackClientScript = buildWritebackClientScript(options.writeback);
  const packMetadata = assetMode === 'inline' ? '' : buildPackMetadataTags(packAssetRecords);
  const writebackMetadata = buildWritebackMetadataTags(options.writeback);
  const packStyleLinks = buildPackStyleLinks(packAssetRecords, assetMode);
  const packModuleScripts = buildPackModuleScripts(packAssetRecords, assetMode);
  const componentScript = buildComponentScript(assetMode, missingBundleComment);
  const mermaidScripts = hasMermaidDiagrams(body) ? buildMermaidScripts(assetMode) : '';

  const mainBody = options.showSource ? pageBody : [buildTableOfContents(options.toc), indent(pageBody, 4)]
    .filter(Boolean)
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
${packMetadata}${writebackMetadata}${styles}
  <style>${theme}</style>${packStyleLinks}
</head>
<body>
  <main class="${mainClass}">
${mainBody}
  </main>
${scripts}${writebackClientScript}${mermaidScripts}${componentScript}${packModuleScripts}
</body>
</html>`;
}

function hasMermaidDiagrams(html) {
  return String(html).includes('data-agent-mermaid');
}

function buildTableOfContents(toc = []) {
  const headings = toc.filter((entry) => entry.level >= 2 && entry.level <= 3);
  if (headings.length < 2) {
    return '';
  }

  const items = headings.map((entry) =>
    `      <li class="agent-isles-toc-item agent-isles-toc-item--h${entry.level}"><a href="#${escapeHtml(entry.id)}">${escapeHtml(entry.text)}</a></li>`
  ).join('\n');

  return `    <nav class="agent-isles-toc" aria-label="Table of contents">
      <p class="agent-isles-toc-title">On this page</p>
      <ol>
${items}
      </ol>
    </nav>`;
}

function buildSourceComparison(renderedBody, sourceMarkdown) {
  return `<section class="agent-isles-source-comparison row g-4 align-items-start">
  <aside class="agent-isles-source-pane col-12 col-xl-6" aria-labelledby="agent-isles-source-heading">
    <div class="agent-isles-source-card card shadow-sm">
      <div class="card-header bg-dark text-light">
        <p class="text-uppercase text-info fw-bold small mb-1">Simple source</p>
        <h2 id="agent-isles-source-heading" class="h5 mb-0 text-light">Source Markdown</h2>
      </div>
      <div class="card-body p-0">
        <pre class="agent-isles-source-markdown mb-0"><code class="language-markdown">${escapeHtml(sourceMarkdown)}</code></pre>
      </div>
    </div>
  </aside>
  <section class="agent-isles-rendered-pane col-12 col-xl-6" aria-labelledby="agent-isles-rendered-heading">
    <div class="agent-isles-rendered-card card shadow-sm">
      <div class="card-header bg-white">
        <p class="text-uppercase text-primary fw-bold small mb-1">Expressive output</p>
        <h2 id="agent-isles-rendered-heading" class="h5 mb-0">Rendered output</h2>
      </div>
      <div class="card-body agent-isles-rendered-output">
${indent(renderedBody, 8)}
      </div>
    </div>
  </section>
</section>`;
}

function buildStyles(assetMode) {
  if (assetMode === 'inline') {
    const bootstrapCss = escapeInlineStyle(readFileSync(require.resolve('bootstrap/dist/css/bootstrap.min.css'), 'utf8'));
    const highlightCss = escapeInlineStyle(readFileSync(require.resolve('highlight.js/styles/github-dark.min.css'), 'utf8'));
    return `  <style>
/* Bootstrap CSS */
${bootstrapCss}
  </style>
  <style>
/* Highlight.js CSS */
${highlightCss}
  </style>`;
  }

  if (assetMode === 'local') {
    return `  <link href="./${localAssetDirName}/bootstrap.min.css" rel="stylesheet" />
  <link href="./${localAssetDirName}/github-dark.min.css" rel="stylesheet" />`;
  }

  return `  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    crossorigin="anonymous"
  />
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css"
    rel="stylesheet"
  />`;
}

function buildScripts(assetMode, missingBundleComment) {
  let bootstrapScript;

  if (assetMode === 'inline') {
    const bootstrapJs = escapeInlineScript(readFileSync(require.resolve('bootstrap/dist/js/bootstrap.bundle.min.js'), 'utf8'));
    bootstrapScript = `  <script>
/* Bootstrap JS */
${bootstrapJs}
  </script>`;
  } else if (assetMode === 'local') {
    bootstrapScript = `  <script src="./${localAssetDirName}/bootstrap.bundle.min.js"></script>`;
  } else {
    bootstrapScript = `  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    crossorigin="anonymous">
  </script>`;
  }

  return `${bootstrapScript}${missingBundleComment}`;
}

function buildWritebackClientScript(writebackOptions = {}) {
  if (writebackOptions.enabled !== true) {
    return '';
  }

  return `
  <script>
/* Agent Isles local writeback client */
(function () {
  const endpointMeta = document.querySelector('meta[name="agent-isles-writeback-endpoint"]');
  const endpoint = endpointMeta && endpointMeta.getAttribute('content');
  if (!endpoint) {
    return;
  }

  function removeError(input) {
    const existing = input.parentElement && input.parentElement.querySelector('.agent-isles-writeback-error');
    if (existing) {
      existing.remove();
    }
  }

  function showError(input, message) {
    removeError(input);
    const error = document.createElement('span');
    error.className = 'agent-isles-writeback-error text-danger small ms-2';
    error.setAttribute('role', 'alert');
    error.textContent = 'Writeback failed: ' + message;
    input.insertAdjacentElement('afterend', error);
  }

  async function submitCheckboxWriteback(input) {
    const previousChecked = !input.checked;
    const rawMetadata = input.getAttribute('data-agent-isles-writeback');
    if (!rawMetadata) {
      return;
    }

    let request;
    try {
      const metadata = JSON.parse(rawMetadata);
      request = {
        ...metadata,
        operation: {
          ...(metadata.operation || {}),
          payload: {
            ...(metadata.operation && metadata.operation.payload ? metadata.operation.payload : {}),
            checked: input.checked,
          },
        },
      };
    } catch (error) {
      input.checked = previousChecked;
      showError(input, 'invalid source metadata');
      return;
    }

    input.disabled = true;
    removeError(input);
    try {
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(request),
      });
      const payload = await response.json().catch(() => ({}));
      if (!response.ok || payload.ok !== true) {
        throw new Error((payload.error && payload.error.message) || payload.message || 'request was rejected');
      }
      request.sourceVersion = payload.nextSourceVersion || request.sourceVersion;
      if (request.target && request.target.anchor) {
        request.target.anchor.text = input.checked ? '[x]' : '[ ]';
      }
      input.setAttribute('data-agent-isles-writeback', JSON.stringify(request));
    } catch (error) {
      input.checked = previousChecked;
      showError(input, error && error.message ? error.message : String(error));
      console.warn('Agent Isles writeback failed:', error);
    } finally {
      input.disabled = false;
    }
  }

  document.addEventListener('change', (event) => {
    const input = event.target;
    if (!(input instanceof HTMLInputElement)) {
      return;
    }
    if (input.type !== 'checkbox' || !input.hasAttribute('data-agent-isles-writeback')) {
      return;
    }
    void submitCheckboxWriteback(input);
  });
}());
  </script>`;
}

function buildMermaidScripts(assetMode) {
  return `\n${buildMermaidRuntimeScript(assetMode)}\n${buildMermaidRendererScript()}`;
}

function buildMermaidRuntimeScript(assetMode) {
  if (assetMode === 'inline') {
    const mermaidRuntime = escapeInlineScript(readFileSync(mermaidRuntimePath, 'utf8'));
    return `  <script>
/* Mermaid runtime */
${mermaidRuntime}
  </script>`;
  }

  const src = assetMode === 'local' ? `./${localAssetDirName}/${mermaidRuntimeName}` : mermaidCdnUrl;
  return `  <script src="${src}"></script>`;
}

function buildMermaidRendererScript() {
  return `  <script>
/* Agent Isles Mermaid renderer */
(function () {
  const figures = Array.from(document.querySelectorAll('[data-agent-mermaid]'));
  if (figures.length === 0) {
    return;
  }

  const mermaid = globalThis.mermaid;
  const showError = (figure, sourceElement, message) => {
    const errorBlock = document.createElement('pre');
    errorBlock.className = 'agent-mermaid-error';
    errorBlock.setAttribute('role', 'alert');
    errorBlock.textContent = 'Mermaid render failed: ' + message;
    sourceElement.insertAdjacentElement('afterend', errorBlock);
    figure.dataset.agentMermaidRendered = 'false';
  };

  if (!mermaid) {
    for (const figure of figures) {
      const sourceElement = figure.querySelector('[data-agent-mermaid-source]');
      if (sourceElement) {
        showError(figure, sourceElement, 'Mermaid runtime failed to load.');
      }
    }
    return;
  }

  mermaid.initialize({
    startOnLoad: false,
    securityLevel: 'strict',
    htmlLabels: false,
  });

  figures.forEach(async (figure, index) => {
    const sourceElement = figure.querySelector('[data-agent-mermaid-source]');
    if (!sourceElement) {
      return;
    }

    const source = sourceElement.textContent || '';
    const output = document.createElement('div');
    output.className = 'agent-mermaid-rendered';
    sourceElement.insertAdjacentElement('afterend', output);

    try {
      if (typeof mermaid.parse === 'function') {
        await mermaid.parse(source);
      }
      const renderResult = await mermaid.render(
        'agent-mermaid-' + index + '-' + Math.random().toString(36).slice(2),
        source,
      );
      output.innerHTML = renderResult.svg;
      sourceElement.hidden = true;
      figure.dataset.agentMermaidRendered = 'true';
    } catch (error) {
      output.remove();
      const message = error && error.message ? error.message : String(error);
      showError(figure, sourceElement, message);
      console.warn('Agent Isles Mermaid render failed:', error);
    }
  });
}());
  </script>`;
}

function buildComponentScript(assetMode, missingBundleComment) {
  if (assetMode === 'inline') {
    if (!existsSync(componentBundlePath)) {
      return missingBundleComment;
    }
    const componentJs = escapeInlineScript(readFileSync(componentBundlePath, 'utf8'));
    return `
  <script type="module">
/* Agent Isles component runtime */
${componentJs}
  </script>`;
  }

  return `
  <script type="module" src="./${componentScriptName}"></script>`;
}

function buildPackMetadataTags(packAssetRecords) {
  if (packAssetRecords.length === 0) {
    return '';
  }

  const packIds = packAssetRecords.map((record) => record.id).join(',');
  return `  <meta name="agent-isles-packs" content="${escapeHtml(packIds)}" />
  <link rel="agent-isles-packs" href="./${packMetadataPath}" type="application/json" />
`;
}

function buildWritebackMetadataTags(writebackOptions = {}) {
  if (writebackOptions.enabled !== true) {
    return '';
  }

  const endpoint = writebackOptions.endpoint || '/__agent-isles/writeback';
  return `  <meta name="agent-isles-writeback-endpoint" content="${escapeHtml(endpoint)}" />
`;
}

// Inline assets land inside raw-text <script>/<style> elements, where a literal
// </script> or </style> would prematurely close the element and corrupt the
// single-file output. Neutralize the end-tag opener so trusted bundles and pack
// assets embed verbatim (the backslash form is inert in JS/CSS string contexts,
// the only place these sequences legitimately appear).
function escapeInlineScript(code) {
  return String(code).replace(/<\/(script)/gi, '<\\/$1');
}

function escapeInlineStyle(code) {
  return String(code).replace(/<\/(style)/gi, '<\\/$1');
}

function readInlinePackAsset(record, asset, kind) {
  if (!asset.resolvedPath || !existsSync(asset.resolvedPath)) {
    throw new AgentIslesInputError(
      `Cannot inline ${kind} asset for pack "${record.id}": declared asset "${asset.path}" was not found` +
        `${asset.resolvedPath ? ` at ${asset.resolvedPath}` : ''}. ` +
        'Ensure the file exists locally, or render with --assets local or --assets cdn instead.',
    );
  }

  const raw = readFileSync(asset.resolvedPath, 'utf8');
  return kind === 'style' ? escapeInlineStyle(raw) : escapeInlineScript(raw);
}

function buildPackStyleLinks(packAssetRecords, assetMode = 'cdn') {
  const styleLinks = packAssetRecords.flatMap((record) => {
    const styleAssets = record.assets.filter((asset) => asset.type === 'style');

    if (assetMode === 'inline') {
      return styleAssets.map((asset) => {
        const css = readInlinePackAsset(record, asset, 'style');
        return `  <style data-agent-isles-pack="${escapeHtml(record.id)}">
/* Pack: ${escapeHtml(record.id)} - ${escapeHtml(asset.path)} */
${css}
  </style>`;
      });
    }

    return styleAssets.map((asset) =>
      `  <link href="${escapeHtml(asset.url)}" rel="stylesheet" data-agent-isles-pack="${escapeHtml(record.id)}" />`
    );
  });

  if (styleLinks.length === 0) {
    return '';
  }

  return `\n${styleLinks.join('\n')}`;
}

function buildPackModuleScripts(packAssetRecords, assetMode = 'cdn') {
  const moduleScripts = packAssetRecords.flatMap((record) => {
    const moduleAssets = record.assets.filter((asset) => asset.type === 'module');

    if (assetMode === 'inline') {
      return moduleAssets.map((asset) => {
        const js = readInlinePackAsset(record, asset, 'module');
        return `  <script type="module" data-agent-isles-pack="${escapeHtml(record.id)}">
/* Pack: ${escapeHtml(record.id)} - ${escapeHtml(asset.path)} */
${js}
  </script>`;
      });
    }

    return moduleAssets.map((asset) =>
      `  <script type="module" src="${escapeHtml(asset.url)}" data-agent-isles-pack="${escapeHtml(record.id)}"></script>`
    );
  });

  if (moduleScripts.length === 0) {
    return '';
  }

  return `\n${moduleScripts.join('\n')}`;
}

export function buildPackAssetRecords(packs = []) {
  const seenSafeIds = new Map();

  return packs.map((pack) => {
    const id = packOwnerId(pack);
    const baseSafeId = safePackId(id);
    const safeIdCount = seenSafeIds.get(baseSafeId) || 0;
    seenSafeIds.set(baseSafeId, safeIdCount + 1);
    const safeId = safeIdCount === 0 ? baseSafeId : `${baseSafeId}-${safeIdCount + 1}`;
    const assets = (pack.assets || []).map((asset) => {
      const normalizedPath = normalizePackAssetPath(pack, asset);
      const outputPath = joinUrlPaths(packAssetRootPath, safeId, normalizedPath);

      return {
        ...asset,
        normalizedPath,
        outputPath,
        url: `./${outputPath}`,
      };
    });

    return {
      pack,
      id,
      safeId,
      assets,
    };
  });
}

function packOwnerId(pack) {
  return pack.version ? `${pack.name}@${pack.version}` : pack.name;
}

function safePackId(packId) {
  const safeId = String(packId)
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');

  return safeId || 'pack';
}

function normalizePackAssetPath(pack, asset) {
  const assetPath = asset.resolvedPath && pack.packDir
    ? relative(pack.packDir, asset.resolvedPath)
    : asset.path;
  const normalizedPath = String(assetPath)
    .split(/[\\/]+/)
    .filter(Boolean)
    .join('/');

  if (!normalizedPath || normalizedPath.startsWith('..') || normalizedPath.includes('/../')) {
    throw new Error(`Pack asset path must stay inside the pack directory: ${asset.path}`);
  }

  return normalizedPath;
}

function joinUrlPaths(...parts) {
  return parts
    .flatMap((part) => String(part).split('/'))
    .filter(Boolean)
    .join('/');
}

function writePackMetadata(outDir, packAssetRecords) {
  if (packAssetRecords.length === 0) {
    return;
  }

  const metadataFile = join(outDir, packMetadataPath);
  mkdirSync(dirname(metadataFile), { recursive: true });
  writeFileSync(metadataFile, `${JSON.stringify(buildPackMetadata(packAssetRecords), null, 2)}\n`);
}

function buildPackMetadata(packAssetRecords) {
  return {
    agentIslesPacksVersion: 1,
    packs: packAssetRecords.map((record) => ({
      id: record.id,
      safeId: record.safeId,
      name: record.pack.name,
      version: record.pack.version,
      description: record.pack.description,
      homepage: record.pack.homepage,
      tags: record.pack.tags || [],
      assets: record.assets.map((asset) => ({
        type: asset.type,
        path: asset.path,
        outputPath: asset.outputPath,
      })),
    })),
  };
}

function copyPackAssets(outDir, packAssetRecords) {
  for (const record of packAssetRecords) {
    for (const asset of record.assets) {
      if (!existsSync(asset.resolvedPath)) {
        throw new Error(`Pack asset source missing: ${asset.resolvedPath}`);
      }

      const destination = join(outDir, asset.outputPath);
      mkdirSync(dirname(destination), { recursive: true });
      copyFileSync(asset.resolvedPath, destination);
    }
  }
}

function readTheme() {
  if (!existsSync(themePath)) {
    return '/* Agent Isles theme missing */';
  }

  return readFileSync(themePath, 'utf8');
}

function copyComponentBundle(outDir) {
  if (!existsSync(componentBundlePath)) {
    return;
  }

  copyFileSync(componentBundlePath, join(outDir, componentScriptName));
}

function copyLocalAssets(outDir) {
  const assetsDir = join(outDir, localAssetDirName);
  mkdirSync(assetsDir, { recursive: true });

  for (const asset of localAssets) {
    if (!existsSync(asset.source)) {
      throw new Error(`Local asset source missing: ${asset.source}`);
    }
    copyFileSync(asset.source, join(assetsDir, asset.fileName));
  }
}

function copyMermaidRuntime(outDir) {
  if (!existsSync(mermaidRuntimePath)) {
    throw new Error(`Mermaid runtime source missing: ${mermaidRuntimePath}`);
  }

  const assetsDir = join(outDir, localAssetDirName);
  mkdirSync(assetsDir, { recursive: true });
  copyFileSync(mermaidRuntimePath, join(assetsDir, mermaidRuntimeName));
}

function normalizeAssetMode(assetMode = 'cdn') {
  if (assetMode === 'cdn' || assetMode === 'local' || assetMode === 'inline') {
    return assetMode;
  }

  throw new Error(`Unsupported asset mode: ${assetMode}. Expected "cdn", "local", or "inline".`);
}

function indent(text, spaces) {
  const prefix = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line ? `${prefix}${line}` : line))
    .join('\n');
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}
