import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, extname, join, relative, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkRehype from 'remark-rehype';
import rehypeRaw from 'rehype-raw';
import { D2 } from '@terrastruct/d2';
import rehypeHighlight from 'rehype-highlight';
import rehypeSanitize, { defaultSchema } from 'rehype-sanitize';
import rehypeStringify from 'rehype-stringify';
import { resolvePackInputs } from './pack-resolver.mjs';

const require = createRequire(import.meta.url);
const moduleDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(moduleDir, '..');
const themePath = join(projectRoot, 'src', 'theme', 'agent-theme.css');
const componentBundlePath = join(projectRoot, 'dist', 'agent-components.js');
const componentScriptName = 'agent-components.js';
const markdownExtensions = new Set(['.md', '.markdown']);
const localAssetDirName = 'assets';
const packAssetRootPath = `${localAssetDirName}/agent-isles/packs`;
const packMetadataPath = `${localAssetDirName}/agent-isles/packs.json`;
const localAssets = [
  {
    source: require.resolve('bootstrap/dist/css/bootstrap.min.css'),
    fileName: 'bootstrap.min.css',
  },
  {
    source: require.resolve('bootstrap/dist/css/bootstrap.min.css.map'),
    fileName: 'bootstrap.min.css.map',
  },
  {
    source: require.resolve('highlight.js/styles/github-dark.min.css'),
    fileName: 'github-dark.min.css',
  },
  {
    source: require.resolve('bootstrap/dist/js/bootstrap.bundle.min.js'),
    fileName: 'bootstrap.bundle.min.js',
  },
  {
    source: require.resolve('bootstrap/dist/js/bootstrap.bundle.min.js.map'),
    fileName: 'bootstrap.bundle.min.js.map',
  },
];

export class AgentIslesInputError extends Error {
  constructor(message, code) {
    super(message);
    this.name = 'AgentIslesInputError';
    this.code = code;
  }
}

export function validateMarkdownInput(inputPath) {
  const filePath = resolve(inputPath);

  if (!existsSync(filePath)) {
    throw new AgentIslesInputError(
      `Input file not found: ${filePath}`,
      'ERR_AGENT_ISLES_INPUT_NOT_FOUND',
    );
  }

  const extension = extname(filePath).toLowerCase();
  if (!markdownExtensions.has(extension)) {
    throw new AgentIslesInputError(
      `Unsupported input file extension: ${filePath}\nExpected a Markdown file ending in .md or .markdown.`,
      'ERR_AGENT_ISLES_UNSUPPORTED_INPUT_EXTENSION',
    );
  }

  return filePath;
}

export const RENDER_MODES = Object.freeze({
  TRUSTED: 'trusted',
  SANITIZED: 'sanitized',
});

const coreSanitizedSchema = {
  ...defaultSchema,
  tagNames: [
    ...new Set([
      ...(defaultSchema.tagNames || []),
      'agent-decision',
      'agent-risk',
      'agent-metric',
      'agent-delta',
      'agent-copy-block',
      'agent-tabs',
      'agent-tab',
      'agent-timeline',
      'agent-step',
      'agent-gantt',
      'agent-gantt-phase',
      'agent-gantt-task',
      'agent-kpi',
      'agent-status-board',
      'agent-status-item',
      'agent-dependency-map',
      'agent-dependency',
      'agent-action-list',
      'agent-action',
      // D2 diagram support (generated by rehype-d2)
      'figure',
      'svg',
      'g',
      'rect',
      'path',
      'text',
      'tspan',
      'defs',
      'marker',
      'line',
      'polygon',
      'polyline',
      'circle',
      'ellipse',
      'clipPath',
      'mask',
      'use',
      'style',
      'title',
      'desc',
    ]),
  ],
  attributes: {
    ...defaultSchema.attributes,
    '*': [
      'className',
      'data*',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.['*'] || []),
    ],
    a: [
      'className',
      'target',
      'rel',
      'role',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.a || []),
    ],
    div: [
      'className',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.div || []),
    ],
    span: [
      'className',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.span || []),
    ],
    img: [
      'className',
      'alt',
      'src',
      'title',
      'role',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.img || []),
    ],
    code: ['className', ...(defaultSchema.attributes?.code || [])],
    pre: ['className', ...(defaultSchema.attributes?.pre || [])],
    'agent-decision': ['className', 'title', 'verdict'],
    'agent-risk': ['className', 'title', 'level'],
    'agent-metric': ['className', 'label', 'value', 'unit', 'trend', 'tone'],
    'agent-delta': ['className', 'label', 'value', 'unit', 'percent', 'direction', 'tone'],
    'agent-copy-block': ['className', 'label', 'lang'],
    'agent-tabs': ['className', 'label'],
    'agent-tab': ['className', 'title', 'active'],
    'agent-timeline': ['className', 'label'],
    'agent-step': ['className', 'status', 'label'],
    'agent-gantt': ['className', 'weeks', 'milestones', 'label'],
    'agent-gantt-phase': ['className', 'label'],
    'agent-gantt-task': ['className', 'label', 'start', 'end', 'tone', 'detail', 'parallel'],
    'agent-kpi': ['className', 'label', 'value', 'unit', 'delta', 'tone'],
    'agent-status-board': ['className', 'label', 'meta', 'summary', 'group-by'],
    'agent-status-item': ['className', 'label', 'status', 'owner', 'updated', 'history'],
    'agent-dependency-map': ['className', 'label', 'direction', 'legend'],
    'agent-dependency': [
      'className',
      'id',
      'label',
      'status',
      'blockedBy',
      'blocked-by',
      'owner',
      'priority',
      'href',
    ],
    'agent-action-list': [
      'className',
      'label',
      'layout',
      'group-by',
      'filter-status',
      'filter-priority',
      'show-done',
    ],
    'agent-action': ['className', 'owner', 'due', 'priority', 'status'],
    // D2 diagram SVG attributes
    figure: ['className'],
    svg: [
      'className',
      'xmlns',
      'xmlnsXlink',
      'xmlns:xlink',
      'viewBox',
      'width',
      'height',
      'preserveAspectRatio',
    ],
    g: ['className', 'id', 'transform', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    rect: [
      'className',
      'x',
      'y',
      'width',
      'height',
      'rx',
      'ry',
      'fill',
      'stroke',
      'strokeWidth',
      'stroke-width',
    ],
    path: ['className', 'd', 'fill', 'stroke', 'strokeWidth', 'stroke-width', 'transform'],
    text: [
      'className',
      'x',
      'y',
      'dx',
      'dy',
      'fill',
      'fontSize',
      'font-size',
      'fontFamily',
      'font-family',
      'fontWeight',
      'font-weight',
      'textAnchor',
      'text-anchor',
      'dominantBaseline',
      'dominant-baseline',
      'transform',
    ],
    tspan: [
      'className',
      'x',
      'y',
      'dx',
      'dy',
      'fill',
      'fontSize',
      'font-size',
      'fontWeight',
      'font-weight',
    ],
    line: [
      'className',
      'x1',
      'y1',
      'x2',
      'y2',
      'stroke',
      'strokeWidth',
      'stroke-width',
      'markerStart',
      'marker-start',
      'markerEnd',
      'marker-end',
    ],
    polygon: ['className', 'points', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    polyline: ['className', 'points', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    circle: ['className', 'cx', 'cy', 'r', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    ellipse: [
      'className',
      'cx',
      'cy',
      'rx',
      'ry',
      'fill',
      'stroke',
      'strokeWidth',
      'stroke-width',
    ],
    marker: [
      'className',
      'id',
      'markerWidth',
      'markerHeight',
      'refX',
      'refY',
      'orient',
      'markerUnits',
    ],
    defs: ['className'],
    clipPath: ['className', 'id'],
    mask: ['className', 'id'],
    use: ['className', 'href', 'xlinkHref', 'xlink:href', 'x', 'y'],
  },
};

function buildSanitizedSchema(resolvedPacks) {
  const tagNames = new Set(coreSanitizedSchema.tagNames || []);
  const attributes = copySchemaAttributes(coreSanitizedSchema.attributes);

  for (const pack of resolvedPacks?.packs || []) {
    for (const tag of pack.tags || []) {
      if (!tag?.name) {
        continue;
      }

      tagNames.add(tag.name);
      const declaredAttributes = (tag.attributes || []).filter(isSafePackDeclaredAttribute);
      if (declaredAttributes.length === 0) {
        continue;
      }

      attributes[tag.name] = [
        ...new Set([
          ...(attributes[tag.name] || []),
          ...declaredAttributes,
        ]),
      ];
    }
  }

  return {
    ...coreSanitizedSchema,
    tagNames: [...tagNames],
    attributes,
  };
}

function copySchemaAttributes(attributes = {}) {
  return Object.fromEntries(
    Object.entries(attributes).map(([tagName, allowedAttributes]) => [
      tagName,
      [...allowedAttributes],
    ]),
  );
}

function isSafePackDeclaredAttribute(attributeName) {
  const normalizedName = String(attributeName).toLowerCase();

  return !normalizedName.startsWith('on') && normalizedName !== 'style' && normalizedName !== 'srcdoc';
}

export async function renderMarkdown(markdown, options = {}) {
  const renderMode = normalizeRenderMode(options.renderMode);
  const assetMode = normalizeAssetMode(options.assetMode);
  const sourceMarkdown = typeof options.sourceMarkdown === 'string' ? options.sourceMarkdown : markdown;
  const processor = unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype, { allowDangerousHtml: true })
    .use(rehypeAgentD2)
    .use(rehypeRaw);

  if (renderMode === RENDER_MODES.SANITIZED) {
    processor
      .use(dropUnsafeRawHtmlElements)
      .use(rehypeSanitize, buildSanitizedSchema(options.resolvedPacks));
  }

  const body = await processor
    .use(rehypeHighlight)
    .use(rehypeStringify, { allowDangerousHtml: renderMode === RENDER_MODES.TRUSTED })
    .process(markdown);

  return buildHtmlPage(String(body), { ...options, renderMode, assetMode, sourceMarkdown });
}

export async function renderMarkdownFile(inputPath, options = {}) {
  const filePath = validateMarkdownInput(inputPath);
  const markdown = readFileSync(filePath, 'utf8');
  const outFile = options.outFile ? resolve(options.outFile) : undefined;
  const assetMode = normalizeAssetMode(options.assetMode);
  const resolvedPacks = await resolvePackInputs({
    explicitPacks: options.explicitPacks || [],
    projectDir: options.projectDir ?? dirname(filePath),
    includeUserPacks: options.includeUserPacks === true,
    userConfigDir: options.userConfigDir || null,
  });
  const packAssetRecords = buildPackAssetRecords(resolvedPacks.packs);
  const html = await renderMarkdown(markdown, {
    ...options,
    assetMode,
    sourcePath: filePath,
    resolvedPacks,
    packAssetRecords,
  });

  if (outFile) {
    mkdirSync(dirname(outFile), { recursive: true });
    writeFileSync(outFile, html);
    if (assetMode !== 'inline') {
      copyComponentBundle(dirname(outFile));
      if (assetMode === 'local') {
        copyLocalAssets(dirname(outFile));
      }
      copyPackAssets(dirname(outFile), packAssetRecords);
      writePackMetadata(dirname(outFile), packAssetRecords);
    }
  }

  return { html, outFile, resolvedPacks };
}

function rehypeAgentD2() {
  return async (tree) => {
    await transformD2CodeBlocks(tree);
  };
}

async function transformD2CodeBlocks(node) {
  if (!Array.isArray(node.children)) {
    return;
  }

  for (let index = 0; index < node.children.length; index += 1) {
    const child = node.children[index];
    const d2Code = extractD2CodeBlock(child);

    if (d2Code) {
      const svg = await renderD2Svg(d2Code.value, child.position);
      node.children[index] = {
        type: 'element',
        tagName: 'figure',
        properties: { className: ['beoe', 'd2'] },
        children: [{ type: 'raw', value: svg }],
      };
      continue;
    }

    await transformD2CodeBlocks(child);
  }
}

function extractD2CodeBlock(node) {
  if (node?.type !== 'element' || node.tagName !== 'pre') {
    return null;
  }

  const codeNode = node.children?.find((child) => child.type === 'element' && child.tagName === 'code');
  const classNames = codeNode?.properties?.className || [];
  const hasD2Language = Array.isArray(classNames)
    ? classNames.includes('language-d2')
    : String(classNames).split(/\s+/).includes('language-d2');

  if (!hasD2Language) {
    return null;
  }

  return {
    value: codeNode.children?.map((child) => child.value || '').join('') || '',
  };
}

async function renderD2Svg(source, position) {
  const d2 = new D2();

  try {
    const result = await d2.compile(source, { noXMLTag: true });
    return await d2.render(result.diagram, { ...result.renderOptions, noXMLTag: true });
  } catch (error) {
    const location = formatPosition(position);
    const message = error?.message || String(error);
    throw new Error(`D2 diagram render failed${location}: ${message}`);
  } finally {
    await d2.worker?.terminate?.();
  }
}

function formatPosition(position) {
  const start = position?.start;
  if (!start?.line) {
    return '';
  }

  return ` at line ${start.line}${start.column ? `, column ${start.column}` : ''}`;
}

export function defaultOutFile(inputPath) {
  const filePath = resolve(inputPath);
  const ext = extname(filePath);
  const baseName = basename(ext ? filePath.slice(0, -ext.length) : filePath);
  return resolve('dist', `${baseName || 'output'}.html`);
}

export function normalizeRenderMode(renderMode = RENDER_MODES.TRUSTED) {
  if (renderMode === RENDER_MODES.TRUSTED || renderMode === RENDER_MODES.SANITIZED) {
    return renderMode;
  }

  throw new Error(
    `Unknown render mode: ${renderMode}. Use "${RENDER_MODES.TRUSTED}" or "${RENDER_MODES.SANITIZED}".`,
  );
}

function dropUnsafeRawHtmlElements() {
  const blockedTagNames = new Set(['script', 'style', 'iframe', 'object', 'embed']);

  return (tree) => {
    visitChildren(tree, (children, index, node) => {
      if (node.type === 'element' && blockedTagNames.has(node.tagName)) {
        children.splice(index, 1);
        return index;
      }

      return undefined;
    });
  };
}

function visitChildren(node, visitor) {
  if (!Array.isArray(node.children)) {
    return;
  }

  for (let index = 0; index < node.children.length; index += 1) {
    const child = node.children[index];
    const nextIndex = visitor(node.children, index, child);

    if (typeof nextIndex === 'number') {
      index = nextIndex - 1;
      continue;
    }

    visitChildren(child, visitor);
  }
}

function buildHtmlPage(body, options = {}) {
  const title = options.title || 'Agent Isles Output';
  const assetMode = normalizeAssetMode(options.assetMode);
  const theme = readTheme();
  const packAssetRecords = options.packAssetRecords || buildPackAssetRecords(options.resolvedPacks?.packs || []);
  const mainClass = options.showSource
    ? 'agent-isles-page agent-isles-page--source-view container-fluid py-4'
    : 'agent-isles-page container py-4';
  const pageBody = options.showSource ? buildSourceComparison(body, options.sourceMarkdown || '') : body;
  const missingBundleComment = existsSync(componentBundlePath)
    ? ''
    : '\n  <!-- Agent Isles warning: dist/agent-components.js is missing. Run `npm run build`. -->';
  const styles = buildStyles(assetMode);
  const scripts = buildScripts(assetMode, missingBundleComment);
  const packMetadata = buildPackMetadataTags(packAssetRecords);
  const packStyleLinks = buildPackStyleLinks(packAssetRecords, assetMode);
  const packModuleScripts = buildPackModuleScripts(packAssetRecords, assetMode);
  const componentScript = buildComponentScript(assetMode, missingBundleComment);

  const mainBody = options.showSource ? pageBody : indent(pageBody, 4);

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
${packMetadata}${styles}
  <style>${theme}</style>${packStyleLinks}
</head>
<body>
  <main class="${mainClass}">
${mainBody}
  </main>
${scripts}${componentScript}${packModuleScripts}
</body>
</html>`;
}

function buildSourceComparison(renderedBody, sourceMarkdown) {
  return `<section class="agent-isles-source-comparison row g-4 align-items-start">
  <aside class="agent-isles-source-pane col-12 col-xl-6" aria-labelledby="agent-isles-source-heading">
    <div class="agent-isles-source-card card shadow-sm">
      <div class="card-header bg-dark text-light">
        <p class="text-uppercase text-info fw-bold small mb-1">Simple source</p>
        <h2 id="agent-isles-source-heading" class="h5 mb-0 text-light">Source Markdown</h2>
      </div>
      <div class="card-body p-0">
        <pre class="agent-isles-source-markdown mb-0"><code class="language-markdown">${escapeHtml(sourceMarkdown)}</code></pre>
      </div>
    </div>
  </aside>
  <section class="agent-isles-rendered-pane col-12 col-xl-6" aria-labelledby="agent-isles-rendered-heading">
    <div class="agent-isles-rendered-card card shadow-sm">
      <div class="card-header bg-white">
        <p class="text-uppercase text-primary fw-bold small mb-1">Expressive output</p>
        <h2 id="agent-isles-rendered-heading" class="h5 mb-0">Rendered output</h2>
      </div>
      <div class="card-body agent-isles-rendered-output">
${indent(renderedBody, 8)}
      </div>
    </div>
  </section>
</section>`;
}

function buildStyles(assetMode) {
  if (assetMode === 'inline') {
    const bootstrapCss = readFileSync(require.resolve('bootstrap/dist/css/bootstrap.min.css'), 'utf8');
    const highlightCss = readFileSync(require.resolve('highlight.js/styles/github-dark.min.css'), 'utf8');
    return `  <style>
/* Bootstrap CSS */
${bootstrapCss}
  </style>
  <style>
/* Highlight.js CSS */
${highlightCss}
  </style>`;
  }

  if (assetMode === 'local') {
    return `  <link href="./${localAssetDirName}/bootstrap.min.css" rel="stylesheet" />
  <link href="./${localAssetDirName}/github-dark.min.css" rel="stylesheet" />`;
  }

  return `  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    crossorigin="anonymous"
  />
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css"
    rel="stylesheet"
  />`;
}

function buildScripts(assetMode, missingBundleComment) {
  let bootstrapScript;

  if (assetMode === 'inline') {
    const bootstrapJs = readFileSync(require.resolve('bootstrap/dist/js/bootstrap.bundle.min.js'), 'utf8');
    bootstrapScript = `  <script>
/* Bootstrap JS */
${bootstrapJs}
  </script>`;
  } else if (assetMode === 'local') {
    bootstrapScript = `  <script src="./${localAssetDirName}/bootstrap.bundle.min.js"></script>`;
  } else {
    bootstrapScript = `  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    crossorigin="anonymous">
  </script>`;
  }

  return `${bootstrapScript}${missingBundleComment}`;
}

function buildComponentScript(assetMode, missingBundleComment) {
  if (assetMode === 'inline') {
    if (!existsSync(componentBundlePath)) {
      return missingBundleComment;
    }
    const componentJs = readFileSync(componentBundlePath, 'utf8');
    return `
  <script type="module">
/* Agent Isles component runtime */
${componentJs}
  </script>`;
  }

  return `
  <script type="module" src="./${componentScriptName}"></script>`;
}

function buildPackMetadataTags(packAssetRecords) {
  if (packAssetRecords.length === 0) {
    return '';
  }

  const packIds = packAssetRecords.map((record) => record.id).join(',');
  return `  <meta name="agent-isles-packs" content="${escapeHtml(packIds)}" />
  <link rel="agent-isles-packs" href="./${packMetadataPath}" type="application/json" />
`;
}

function buildPackStyleLinks(packAssetRecords, assetMode = 'cdn') {
  const styleLinks = packAssetRecords.flatMap((record) => {
    const styleAssets = record.assets.filter((asset) => asset.type === 'style');

    if (assetMode === 'inline') {
      return styleAssets.map((asset) => {
        if (!existsSync(asset.resolvedPath)) {
          return `  <!-- Pack style missing: ${escapeHtml(asset.path)} -->`;
        }
        const css = readFileSync(asset.resolvedPath, 'utf8');
        return `  <style data-agent-isles-pack="${escapeHtml(record.id)}">
/* Pack: ${escapeHtml(record.id)} - ${escapeHtml(asset.path)} */
${css}
  </style>`;
      });
    }

    return styleAssets.map((asset) =>
      `  <link href="${escapeHtml(asset.url)}" rel="stylesheet" data-agent-isles-pack="${escapeHtml(record.id)}" />`
    );
  });

  if (styleLinks.length === 0) {
    return '';
  }

  return `\n${styleLinks.join('\n')}`;
}

function buildPackModuleScripts(packAssetRecords, assetMode = 'cdn') {
  const moduleScripts = packAssetRecords.flatMap((record) => {
    const moduleAssets = record.assets.filter((asset) => asset.type === 'module');

    if (assetMode === 'inline') {
      return moduleAssets.map((asset) => {
        if (!existsSync(asset.resolvedPath)) {
          return `  <!-- Pack module missing: ${escapeHtml(asset.path)} -->`;
        }
        const js = readFileSync(asset.resolvedPath, 'utf8');
        return `  <script type="module" data-agent-isles-pack="${escapeHtml(record.id)}">
/* Pack: ${escapeHtml(record.id)} - ${escapeHtml(asset.path)} */
${js}
  </script>`;
      });
    }

    return moduleAssets.map((asset) =>
      `  <script type="module" src="${escapeHtml(asset.url)}" data-agent-isles-pack="${escapeHtml(record.id)}"></script>`
    );
  });

  if (moduleScripts.length === 0) {
    return '';
  }

  return `\n${moduleScripts.join('\n')}`;
}

export function buildPackAssetRecords(packs = []) {
  const seenSafeIds = new Map();

  return packs.map((pack) => {
    const id = packOwnerId(pack);
    const baseSafeId = safePackId(id);
    const safeIdCount = seenSafeIds.get(baseSafeId) || 0;
    seenSafeIds.set(baseSafeId, safeIdCount + 1);
    const safeId = safeIdCount === 0 ? baseSafeId : `${baseSafeId}-${safeIdCount + 1}`;
    const assets = (pack.assets || []).map((asset) => {
      const normalizedPath = normalizePackAssetPath(pack, asset);
      const outputPath = joinUrlPaths(packAssetRootPath, safeId, normalizedPath);

      return {
        ...asset,
        normalizedPath,
        outputPath,
        url: `./${outputPath}`,
      };
    });

    return {
      pack,
      id,
      safeId,
      assets,
    };
  });
}

function packOwnerId(pack) {
  return pack.version ? `${pack.name}@${pack.version}` : pack.name;
}

function safePackId(packId) {
  const safeId = String(packId)
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');

  return safeId || 'pack';
}

function normalizePackAssetPath(pack, asset) {
  const assetPath = asset.resolvedPath && pack.packDir
    ? relative(pack.packDir, asset.resolvedPath)
    : asset.path;
  const normalizedPath = String(assetPath)
    .split(/[\\/]+/)
    .filter(Boolean)
    .join('/');

  if (!normalizedPath || normalizedPath.startsWith('..') || normalizedPath.includes('/../')) {
    throw new Error(`Pack asset path must stay inside the pack directory: ${asset.path}`);
  }

  return normalizedPath;
}

function joinUrlPaths(...parts) {
  return parts
    .flatMap((part) => String(part).split('/'))
    .filter(Boolean)
    .join('/');
}

function writePackMetadata(outDir, packAssetRecords) {
  if (packAssetRecords.length === 0) {
    return;
  }

  const metadataFile = join(outDir, packMetadataPath);
  mkdirSync(dirname(metadataFile), { recursive: true });
  writeFileSync(metadataFile, `${JSON.stringify(buildPackMetadata(packAssetRecords), null, 2)}\n`);
}

function buildPackMetadata(packAssetRecords) {
  return {
    agentIslesPacksVersion: 1,
    packs: packAssetRecords.map((record) => ({
      id: record.id,
      safeId: record.safeId,
      name: record.pack.name,
      version: record.pack.version,
      description: record.pack.description,
      homepage: record.pack.homepage,
      tags: record.pack.tags || [],
      assets: record.assets.map((asset) => ({
        type: asset.type,
        path: asset.path,
        outputPath: asset.outputPath,
      })),
    })),
  };
}

function copyPackAssets(outDir, packAssetRecords) {
  for (const record of packAssetRecords) {
    for (const asset of record.assets) {
      if (!existsSync(asset.resolvedPath)) {
        throw new Error(`Pack asset source missing: ${asset.resolvedPath}`);
      }

      const destination = join(outDir, asset.outputPath);
      mkdirSync(dirname(destination), { recursive: true });
      copyFileSync(asset.resolvedPath, destination);
    }
  }
}

function readTheme() {
  if (!existsSync(themePath)) {
    return '/* Agent Isles theme missing */';
  }

  return readFileSync(themePath, 'utf8');
}

function copyComponentBundle(outDir) {
  if (!existsSync(componentBundlePath)) {
    return;
  }

  copyFileSync(componentBundlePath, join(outDir, componentScriptName));
}

function copyLocalAssets(outDir) {
  const assetsDir = join(outDir, localAssetDirName);
  mkdirSync(assetsDir, { recursive: true });

  for (const asset of localAssets) {
    if (!existsSync(asset.source)) {
      throw new Error(`Local asset source missing: ${asset.source}`);
    }
    copyFileSync(asset.source, join(assetsDir, asset.fileName));
  }
}

function normalizeAssetMode(assetMode = 'cdn') {
  if (assetMode === 'cdn' || assetMode === 'local' || assetMode === 'inline') {
    return assetMode;
  }

  throw new Error(`Unsupported asset mode: ${assetMode}. Expected "cdn", "local", or "inline".`);
}

function indent(text, spaces) {
  const prefix = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line ? `${prefix}${line}` : line))
    .join('\n');
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}
