import { defaultSchema } from 'rehype-sanitize';

const coreSanitizedSchema = {
  ...defaultSchema,
  tagNames: [
    ...new Set([
      ...(defaultSchema.tagNames || []),
      'agent-choice',
      'agent-decision',
      'agent-option-set',
      'agent-risk',
      'agent-metric',
      'agent-delta',
      'agent-copy-block',
      'agent-theme-toggle',
      'agent-tabs',
      'agent-tab',
      'agent-timeline',
      'agent-step',
      'agent-gantt',
      'agent-gantt-phase',
      'agent-gantt-task',
      'agent-kpi',
      'agent-status-board',
      'agent-status-item',
      'agent-dependency-map',
      'agent-dependency',
      'agent-action-list',
      'agent-action',
      'agent-kanban',
      'agent-kanban-lane',
      'agent-kanban-card',
      // D2 diagram support (generated by rehype-d2)
      'figure',
      'svg',
      'g',
      'rect',
      'path',
      'text',
      'tspan',
      'defs',
      'marker',
      'line',
      'polygon',
      'polyline',
      'circle',
      'ellipse',
      'clipPath',
      'mask',
      'use',
      'style',
      'title',
      'desc',
    ]),
  ],
  attributes: {
    ...defaultSchema.attributes,
    '*': [
      'className',
      'data*',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.['*'] || []),
    ],
    a: [
      'className',
      'target',
      'rel',
      'role',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.a || []),
    ],
    div: [
      'className',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.div || []),
    ],
    span: [
      'className',
      'role',
      'title',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.span || []),
    ],
    img: [
      'className',
      'alt',
      'src',
      'title',
      'role',
      'ariaLabel',
      /^aria[A-Z][A-Za-z0-9]*$/,
      /^aria-[a-z][a-z0-9-]*$/,
      ...(defaultSchema.attributes?.img || []),
    ],
    code: ['className', ...(defaultSchema.attributes?.code || [])],
    pre: ['className', 'data*', ...(defaultSchema.attributes?.pre || [])],
    'agent-choice': ['className', 'id', 'title', 'selected'],
    'agent-decision': ['className', 'title', 'verdict'],
    'agent-option-set': ['className', 'data-multiselect'],
    'agent-risk': ['className', 'title', 'level'],
    'agent-metric': ['className', 'label', 'value', 'unit', 'trend', 'tone'],
    'agent-delta': ['className', 'label', 'value', 'unit', 'percent', 'direction', 'tone'],
    'agent-copy-block': ['className', 'label', 'lang'],
    'agent-theme-toggle': ['className', 'label', 'storage-key'],
    'agent-tabs': ['className', 'label'],
    'agent-tab': ['className', 'title', 'active'],
    'agent-timeline': ['className', 'label'],
    'agent-step': ['className', 'status', 'label'],
    'agent-gantt': ['className', 'weeks', 'milestones', 'label'],
    'agent-gantt-phase': ['className', 'label'],
    'agent-gantt-task': ['className', 'label', 'start', 'end', 'tone', 'detail', 'parallel'],
    'agent-kpi': ['className', 'label', 'value', 'unit', 'delta', 'tone'],
    'agent-status-board': ['className', 'label', 'meta', 'summary', 'group-by', 'hide-empty-groups'],
    'agent-status-item': ['className', 'label', 'status', 'status-color', 'status-label', 'owner', 'updated', 'history'],
    'agent-dependency-map': ['className', 'label', 'direction', 'legend'],
    'agent-dependency': [
      'className',
      'id',
      'label',
      'status',
      'blockedBy',
      'blocked-by',
      'owner',
      'priority',
      'href',
    ],
    'agent-action-list': [
      'className',
      'label',
      'layout',
      'group-by',
      'filter-status',
      'filter-priority',
      'show-done',
    ],
    'agent-action': ['className', 'owner', 'due', 'priority', 'status'],
    'agent-kanban': ['className', 'label', 'lanes', 'density'],
    'agent-kanban-lane': ['className', 'key', 'label', 'empty'],
    'agent-kanban-card': ['className', 'title', 'owner', 'meta', 'priority', 'status', 'tone'],
    // D2 diagram SVG attributes
    figure: ['className', 'data*'],
    svg: [
      'className',
      'xmlns',
      'xmlnsXlink',
      'xmlns:xlink',
      'viewBox',
      'width',
      'height',
      'preserveAspectRatio',
    ],
    g: ['className', 'id', 'transform', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    rect: [
      'className',
      'x',
      'y',
      'width',
      'height',
      'rx',
      'ry',
      'fill',
      'stroke',
      'strokeWidth',
      'stroke-width',
    ],
    path: ['className', 'd', 'fill', 'stroke', 'strokeWidth', 'stroke-width', 'transform'],
    text: [
      'className',
      'x',
      'y',
      'dx',
      'dy',
      'fill',
      'fontSize',
      'font-size',
      'fontFamily',
      'font-family',
      'fontWeight',
      'font-weight',
      'textAnchor',
      'text-anchor',
      'dominantBaseline',
      'dominant-baseline',
      'transform',
    ],
    tspan: [
      'className',
      'x',
      'y',
      'dx',
      'dy',
      'fill',
      'fontSize',
      'font-size',
      'fontWeight',
      'font-weight',
    ],
    line: [
      'className',
      'x1',
      'y1',
      'x2',
      'y2',
      'stroke',
      'strokeWidth',
      'stroke-width',
      'markerStart',
      'marker-start',
      'markerEnd',
      'marker-end',
    ],
    polygon: ['className', 'points', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    polyline: ['className', 'points', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    circle: ['className', 'cx', 'cy', 'r', 'fill', 'stroke', 'strokeWidth', 'stroke-width'],
    ellipse: [
      'className',
      'cx',
      'cy',
      'rx',
      'ry',
      'fill',
      'stroke',
      'strokeWidth',
      'stroke-width',
    ],
    marker: [
      'className',
      'id',
      'markerWidth',
      'markerHeight',
      'refX',
      'refY',
      'orient',
      'markerUnits',
    ],
    defs: ['className'],
    clipPath: ['className', 'id'],
    mask: ['className', 'id'],
    use: ['className', 'href', 'xlinkHref', 'xlink:href', 'x', 'y'],
  },
};

export function buildSanitizedSchema(resolvedPacks) {
  const tagNames = new Set(coreSanitizedSchema.tagNames || []);
  const attributes = copySchemaAttributes(coreSanitizedSchema.attributes);

  for (const pack of resolvedPacks?.packs || []) {
    for (const tag of pack.tags || []) {
      if (!tag?.name) {
        continue;
      }

      tagNames.add(tag.name);
      const declaredAttributes = (tag.attributes || []).filter(isSafePackDeclaredAttribute);
      if (declaredAttributes.length === 0) {
        continue;
      }

      attributes[tag.name] = [
        ...new Set([
          ...(attributes[tag.name] || []),
          ...declaredAttributes,
        ]),
      ];
    }
  }

  return {
    ...coreSanitizedSchema,
    tagNames: [...tagNames],
    attributes,
  };
}

function copySchemaAttributes(attributes = {}) {
  return Object.fromEntries(
    Object.entries(attributes).map(([tagName, allowedAttributes]) => [
      tagName,
      [...allowedAttributes],
    ]),
  );
}

function isSafePackDeclaredAttribute(attributeName) {
  const normalizedName = String(attributeName).toLowerCase();

  return !normalizedName.startsWith('on') && normalizedName !== 'style' && normalizedName !== 'srcdoc';
}

export function dropUnsafeRawHtmlElements() {
  const blockedTagNames = new Set(['script', 'style', 'iframe', 'object', 'embed']);

  return (tree) => {
    visitChildren(tree, (children, index, node) => {
      if (node.type === 'element' && blockedTagNames.has(node.tagName)) {
        children.splice(index, 1);
        return index;
      }

      return undefined;
    });
  };
}

function visitChildren(node, visitor) {
  if (!Array.isArray(node.children)) {
    return;
  }

  for (let index = 0; index < node.children.length; index += 1) {
    const child = node.children[index];
    const nextIndex = visitor(node.children, index, child, node);

    if (typeof nextIndex === 'number') {
      index = nextIndex - 1;
      continue;
    }

    visitChildren(child, visitor);
  }
}
